### ISSUE TITLE
Not sure if infinite height corn plants are intended

### ISSUE THREAD

**Issue by faceofcat** [cleverpanda/SimpleCorn#11]
if they are... ignore this...

using bonemeal on the top piece of the plant you can get this:
![image](https://user-images.githubusercontent.com/23014228/31049203-e644f3f2-a636-11e7-9c13-4a646a0ee658.png)

this is on 1.12.1... using latest mod version from curse... 1.12-2.3.2

**Comment by cleverpanda** [comment]
\>.>

**Comment by cleverpanda** [comment]
Fixed in 2.3.5 (?) Give it a try again to be sure if you update

**Comment by faceofcat** [comment]
https://gfycat.com/flatsplendidgoldenmantledgroundsquirrel

still happening
