### ISSUE TITLE
Crash when looking at mid part of corn

### ISSUE THREAD

**Issue by Insane96** [cleverpanda/SimpleCorn#25]
```
java.lang.IllegalAccessError: tried to access field net.minecraft.block.BlockCrops.field_185530_a from class panda.corn.blocks.BlockCornMid
	at panda.corn.blocks.BlockCornMid.func_185496_a(BlockCornMid.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:461)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:357)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1241)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by cleverpanda** [comment]
I *think* I fixed this 2.5.7+

**Comment by Insane96** [comment]
Still an issue as 2.5.8 but the exception changes. I have HYWLA installed.
```
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=simplecorn:corn_mid, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at panda.corn.blocks.BlockCornMid.func_185496_a(BlockCornMid.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456)
	at net.minecraft.block.Block.func_180636_a(Block.java:631)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:461)
	at net.minecraft.world.World.func_147447_a(World.java:1087)
	at net.minecraft.entity.Entity.func_174822_a(Entity.java:1586)
	at net.minecraft.client.renderer.EntityRenderer.func_78473_a(EntityRenderer.java:357)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1241)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by cleverpanda** [comment]
This is actually a different problem.
I will give it a look

**Comment by Insane96** [comment]
This happens even with the top part
