### ISSUE TITLE
[1.16.5] Crash with forge 36.1.24 - NoSuchFieldException: TEMPTATION_ITEMS

### ISSUE THREAD

**Issue by skydark** [cleverpanda/SimpleCorn#36]
No other mods. Crash when starting game.
SimpleCorn: 2.6.0
Crash report:  <https://paste.ee/p/A1dSA>

**Comment by skydark** [comment]
Fixed in v2.6.1. Thanks a lot!

**Comment by cleverpanda** [comment]
Not fixed, taming/breeding feature just removed 'til I have time to fix!
